#!/bin/sh
set_title_text()
{
	if [ -n "$1" ] ; then
		lipc-set-prop com.lab126.pillow configureChrome "{\"titleBar\":{\"clientParams\":{\"secondary\":\"${1}\",\"useDefaultPrimary\":false}}}"
	fi
}

# Well...that was easy.
install_key()
{
	# Install our public key
	cat > "/etc/uks/pubdevkey01.pem" << EOF
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDJn1jWU+xxVv/eRKfCPR9e47lP
WN2rH33z9QbfnqmCxBRLP6mMjGy6APyycQXg3nPi5fcb75alZo+Oh012HpMe9Lnp
eEgloIdm1E4LOsyrz4kttQtGRlzCErmBGt6+cAVEV86y2phOJ3mLk0Ek9UQXbIUf
rvyJnS2MKLG2cczjlQIDAQAB
-----END PUBLIC KEY-----
EOF
	[ $? != 0 ] && return 1
	return 0
}

# Gracefully "exit" the browser.
lipc-set-prop com.lab126.appmgrd start app://com.lab126.booklet.home
sleep 1
set_title_text "JB Starting..."
sleep 3

success=false
# Give the user two minutes to follow our instructions.
for i in $(seq 1 120) ; do
	if install_key ; then
		success=true
		break
	else
		set_title_text "Run ;fc-cache in the search bar."
		sleep 1
	fi
done

if [ "${success}" == "true" ] ; then
    set_title_text "Jailbreak succeeded!"
else
    set_title_text "Jailbreak failed."
fi
